server:
  port: 18010

spring:
  application:
    name: 'app-api'

  config:
    import:
      - "classpath:application-domain.yml"

# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.enabling
# spring-actuator config
management:
  #  server:
  #    port: 18011
  endpoints:
    web:
      #      base-path: "/manage"
      #      path-mapping:
      #        health: "healthcheck"
      exposure:
        include: health #  노출할 엔드포인트 지정
  #         exclude: "env,beans" # 노출되지 않아야 하는 엔드포인트 지정
  endpoint:
    beans:
      cache:
        time-to-live: "10s" #  엔드포인트는 매개변수를 사용하지 않는 읽기 작업에 대한 응답을 자동으로 캐시합니다. 캐시 수명을 변경할 수 있습니다.
    health:
      show-details: always # Health 상태의 자세한 정보를 노출
  health:
    diskspace:
      enabled: false   # 디스크 공간 관련 HealthIndicator 비활성화