server:
  port: 18010

spring:
  application:
    name: 'app-api'

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/woorim
    username: woorim_svc
    password: woorim_svc